whole_clinit = [
    '\n'
    '.method static constructor <clinit>()V\n'
    '    .locals 1\n'
    '\n'
    '    :try_start_0\n'
    '    const-string v0, "nc"\n'
    '\n'
    '    invoke-static {v0}, Ljava/lang/System;->loadLibrary(Ljava/lang/String;)V\n'
    '    :try_end_0\n'
    '    .catch Ljava/lang/UnsatisfiedLinkError; {:try_start_0 .. :try_end_0} :catch_0\n'
    '\n'
    '    goto :goto_0\n'
    '\n'
    '    :catch_0\n'
    '    move-exception v0\n'
    '\n'
    '    .local v0, "e":Ljava/lang/UnsatisfiedLinkError;\n'
    '    invoke-virtual {v0}, Ljava/lang/UnsatisfiedLinkError;->printStackTrace()V\n'
    '\n'
    '    .end local v0    # "e":Ljava/lang/UnsatisfiedLinkError;\n'
    '    :goto_0\n'
    '    return-void\n'
    '.end method\n'
]

insert_clinit = [
    '\n'
    '    :try_start_ab\n'
    '    const-string v0, "nc"\n'
    '\n'
    '    invoke-static {v0}, Ljava/lang/System;->loadLibrary(Ljava/lang/String;)V\n'
    '    :try_end_ab\n'
    '    .catch Ljava/lang/UnsatisfiedLinkError; {:try_start_ab .. :try_end_ab} :catch_ab\n'
    '\n'
    '    goto :goto_ab\n'
    '\n'
    '    :catch_ab\n'
    '    move-exception v0\n'
    '\n'
    '    .local v0, "e":Ljava/lang/UnsatisfiedLinkError;\n'
    '    invoke-virtual {v0}, Ljava/lang/UnsatisfiedLinkError;->printStackTrace()V\n'
    '\n'
    '    .end local v0    # "e":Ljava/lang/UnsatisfiedLinkError;\n'
    '    :goto_ab\n'
]
